name = "SpatialBoundaries"
uuid = "8d2ba62a-3d23-4a2b-b692-6b63e9267be2"
authors = ["Tanya Strydom <tanya.strydom@umontreal.ca>", "Timothée Poisot <timothee.poisot@umontreal.ca>"]
version = "0.0.1"

[deps]
Delaunay = "07eb4e4e-0c6d-46ef-bc4e-83d5e5d860a9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Delaunay = "1.1"
Requires = "1"
StatsBase = "0.33"
julia = "1.6"
